### ISSUE TITLE
[perf] Refactor processing loop to enhance throughput

### ISSUE THREAD

**Issue by Tochemey** [Tochemey/goakt#181]
This requires a better mailbox instead of the current buffered-based channel. Also, the receiving loop and behaviour stacks can be improved to enhance the performance.

**Comment by AlexanderTar** [comment]
@Tochemey I've added #187 to address this issue. The idea is to use a combination of two buffered channels and a small FIFO buffer in between.

**Comment by Tochemey** [comment]
@AlexanderTar Thanks for the PR. I have left some comments on it. I am glad to chat a bit about the idea behind it and am open to a change.

**Comment by Tochemey** [comment]
Thanks @AlexanderTar for this https://github.com/Tochemey/goakt/pull/188 to enhance a bit the performance. I am sure there may be other parts in the code we can enhance.

**Comment by Tochemey** [comment]
This is an ongoing task until we reach an excellent throughput. The current throughput according to the benchmark is relatively good for any application.

**Comment by Tochemey** [comment]
We can always create another issue related to performance when the needs arsises
