### ISSUE TITLE
[feat] Actor redeployment when cluster mode is enabled

### ISSUE THREAD

**Issue by Tochemey** [Tochemey/goakt#192]
The cluster implementation simply relies on a distributed sharded key/value store [engine](https://github.com/buraksezer/olric). It handles the rebalance and the sharding mechanism.

- A single instance of an actor is created when cluster mode is enabled. The actor identifier is propagated across the cluster.
- Each node in the cluster has a copy of the created actor identifier and can easily refers to the location of the actor. 
- When the node where the given actor is created dies, then the other nodes in the cluster are aware of the event. However, at the moment, Go-Akt is not doing actor redeployment which is the issue we need to address.

It is an issue because that actor cannot be found when its node dies

**Comment by Tochemey** [comment]
I suggest a QA be done before tackling this.

**Comment by Tochemey** [comment]
There are two ways to go about this:

- Actor serialization and deserialization: this will require serialize the implemented Actor into some bytes array and pass that data over the wire to be able to deserialize it whenever we need to re-create it.
- Listen to cluster events and recreate actors when there really existed. We don't want to create non existing actors. We know that the given actor reference exist in the cluster even if its hosting node leaves the cluster.

**Comment by Tochemey** [comment]
https://github.com/Tochemey/goakt?tab=readme-ov-file#cluster

**Comment by Tochemey** [comment]
I will look into actors' redeployment.Any help is welcome. cc @AlexanderTar, @chenxyzl and @civilizeddev

**Comment by Tochemey** [comment]
Some thoughts here:

- Add a serializer interface to the `Actor` interface. That way developers can implement their custom binary serialization using [binary encoder](https://pkg.go.dev/encoding#BinaryMarshaler) and [binary decoder](https://pkg.go.dev/encoding#BinaryUnmarshaler). This will help serialize `Actor` implementation and send them over the wire.
- Add an option to cluster mode to start cluster with a minimum number of nodes (at least three). When that number goes below the threshold then we can trigger a panic that the cluster is unbalanced and request an action.
- When a node leaves the cluster, re-creates its actors whenever they are accessed on other nodes in the cluster. This is feasible because the same actor system is run across the cluster.

**Comment by Tochemey** [comment]
I will not be able to work on this at the moment.

**Comment by qazwsxedckll** [comment]
Sorry, but I don't get it. Why serialization is related to redeployment?
I saw the RemoteSpawn method, all it need is the actor type and the actor name. Why not just use it?
I do saw that the Register method is not automatically called when starting the actor system.

Here is my usecase. The user can create a MQTT client on the web and subscribe to some topics. I want to create an actor for each client and when the node is down I need to recreate the actor and subscribe to the topics again. So recreate the actor whenever it is accessed is not going to work for me.
