### ISSUE TITLE
[feat] discovery.HostNode() should accept configs rather than read env directly

### ISSUE THREAD

**Issue by qazwsxedckll** [Tochemey/goakt#300]
Reading and merging env to configs should be handled by user using some modules like `viper` or `koanf`.

To my opinion, I always avoid using env and put all configs in local config files. I have come accross many times that a mysterious env is controlling a key feature and no one knows about it. It is a nightmare to debug.

**Comment by Tochemey** [comment]
Thanks for the suggestion. I will look into it. However there are no hidden env vars and there are all documented only few used for cluster run.
