### ISSUE TITLE
WithMailbox should be a factory

### ISSUE THREAD

**Issue by waeljammal** [Tochemey/goakt#326]
It looks like using `WithMailbox` will register a single mailbox that is then used by all the pids, where as not supplying one will allow each pid to create a new mailbox. Not sure if this is intended, just noticed it while reading through the code.

**Comment by Tochemey** [comment]
Hello @waeljammal,

I hope you are well. Thanks for opening an issue. This option is intended to allow a developer to implement his/her own mailbox and hook it into the actor system. Every actor created will have an instance of the mailbox provided. I hope this helps. However in case you have a suggestion, I welcome PR or sample code we can reason around.

**Comment by Tochemey** [comment]
@waeljammal I have seen the bug. I will push a fix shortly and cut a new tag.
