### ISSUE TITLE
[feat] Examples should in go modules to aviod add dependencies to main module

### ISSUE THREAD

**Issue by qazwsxedckll** [Tochemey/goakt#336]
Use `go work init && go work use -r .`  to add all examples.

Besides, go.work is not recommanded to be commited to the repository.

**Comment by Tochemey** [comment]
@qazwsxedckll thanks for the suggestion. I will be glad if you can open a PR to provide the fix. I will be glad to merge the PR.

**Comment by Tochemey** [comment]
@qazwsxedckll I don't know which dependencies you are referring to because I believe all dependencies in the main module are really needed. Kindly help if you have the bandwidth.

**Comment by qazwsxedckll** [comment]
![image](https://github.com/Tochemey/goakt/assets/20088957/807e4d34-4214-4bb8-ba79-b4294128fe4e)

@Tochemey Something like this. It is in the main module.

**Comment by Tochemey** [comment]
@qazwsxedckll I have moved all the examples into a separate repository. That way anyone can add more examples if need be https://github.com/Tochemey/goakt-examples. Once again thanks for your suggestions and contributions.
