### ISSUE TITLE
[feat] upgrade go version to 1.22.0

### ISSUE THREAD

**Issue by Tochemey** [Tochemey/goakt#353]
This will be come in v2.2.0.

https://github.com/Tochemey/goakt/pull/351

**Comment by Tochemey** [comment]
@qazwsxedckll @AlexanderTar @chenxyzl @civilizeddev what do you guys think? 

The current release is running on go 1.21. However the kubernetes api has moved on to go 1.22. I don't want us to be running an older version of dependencies in the library. The challenge here is if people pin their go version to a lower one then it will be inconvenient for them to use the latest bug fix version of the library.

**Comment by qazwsxedckll** [comment]
Just upgrade it.
