### ISSUE TITLE
Dead lock during child actor spanwing

### ISSUE THREAD

**Issue by zaibon** [Tochemey/goakt#382]
**Bug description**
Dead lock during child actor spanwing

**How to reproduce it?**
Try to spawn a child actor

**Expected behavior**
Process should not dead lock

**Library Version:**
 - Go-Akt version: v2.3.0
 - Go version: 1.22

**Additional context**
The first lock happens here. the unlock is defered https://github.com/Tochemey/goakt/blob/28d2fa945959affbfe123b3110a5a46edc7c73eb/actors/pid.go#L552
The second lock happens here, while the first lock is still active. https://github.com/Tochemey/goakt/blob/28d2fa945959affbfe123b3110a5a46edc7c73eb/internal/eventstream/stream.go#L133

**Comment by Tochemey** [comment]
@zaibon Thanks for reporting. I will take a look.

**Comment by Tochemey** [comment]
@zaibon never mind I think I have found the issue. Doing some digging, hopefully fix it soon.

**Comment by Tochemey** [comment]
@zaibon I will cut a release after the build is done. Once again thanks for reporting this.

**Comment by Tochemey** [comment]
@zaibon this is the new release https://github.com/Tochemey/goakt/releases/tag/v2.3.1

**Comment by zaibon** [comment]
Thanks for the quick response 👍
