### ISSUE TITLE
Cluster re-balancing not working

### ISSUE THREAD

**Issue by webfrank** [Tochemey/goakt#446]
**Bug description**
I created a three node cluster, each node at startup spawns an Actor, if I kill one node I expect the local actor to be rebalanced on some other node.

**How to reproduce it?**
Create a simple system with clustering enabled. Register Actor type. Spawn an Actor. This on three different nodes. Kill one node and the re-balancing gives the error:

{"level":"debug","ts":"2024-08-29T07:54:33Z","msg":"total actors: 2 on node left[172.16.23.26:3320]"}
{"level":"debug","ts":"2024-08-29T07:54:33Z","msg":"re-creating actor=[(mbp2024.local-ping) of type (actors.pid)]"}
{"level":"debug","ts":"2024-08-29T07:54:33Z","msg":"re-creating actor=[(GoAktSupervisorLOCAL172.16.23.26-3321-1724918049452749000) of type (actors.pid)]"}
{"level":"error","ts":"2024-08-29T07:54:33Z","msg":"actor type is not registered"}
{"level":"error","ts":"2024-08-29T07:54:33Z","msg":"canceled: context canceled"}
{"level":"error","ts":"2024-08-29T07:54:33Z","msg":"cluster rebalancing failed: actor type is not registered"}

**Expected behavior**
I expect to re-create the Actor on one of the remaining node

**Screenshots**

**Library Version:**
 - Go-Akt version: 2.6.0
 - Go version: 1.22.2

**Additional context**
Relevant code:
```
	// create the actor system
	actorSystem, err := goakt.NewActorSystem(
		"local",
		goakt.WithPassivationDisabled(), // disable passivation
		goakt.WithLogger(logger),
		goakt.WithActorInitMaxRetries(3),
		goakt.WithRemoting(GetOutboundIP().String(), 3321),
		goakt.WithClustering(disco, 20, 2, 3322, 3320, new(Ping)))
	// handle the error
	if err != nil {
		logger.Panic(err)
	}

	// start the actor system
	if err := actorSystem.Start(ctx); err != nil {
		logger.Panic(err)
	}

	if err := actorSystem.Register(ctx, &Ping{}); err != nil {
		logger.Panic(err)
	}

	pid, err := actorSystem.Spawn(ctx, fmt.Sprintf("%s-ping", host), &Ping{logger: logger})
	if err != nil {
		logger.Errorf("Cannot Spawn Actor: %v", err)
	}
	logger.Infof("Actor PID: %v", pid)
```

**Comment by Tochemey** [comment]
Hello @webfrank. Thanks for reporting this issue. I will take a look. I hope you took a look at these working examples here https://github.com/Tochemey/goakt-examples/tree/main/actor-cluster

**Comment by Tochemey** [comment]
@webfrank I have been able to reproduce the error. I will provide a fix morrow. Thanks

**Comment by Tochemey** [comment]
@webfrank once you set the cluster configuration you don't need to `register` again. Register is ok when not in cluster mode and you would like to allow remote actor creation.

**Comment by Tochemey** [comment]
@webfrank I will run some tests and then close the issue.

**Comment by webfrank** [comment]
Hi, just upgraded to latest commit but got the same error (removed the register part):

```
{"level":"debug","ts":"2024-08-30T08:51:25Z","msg":"total actors: 2 on node left[172.16.23.26:3320]"}
{"level":"debug","ts":"2024-08-30T08:51:25Z","msg":"re-creating actor=[(mbp2024.local-ping) of type (actors.pid)]"}
{"level":"error","ts":"2024-08-30T08:51:25Z","msg":"actor type is not registered"}
{"level":"error","ts":"2024-08-30T08:51:25Z","msg":"cluster rebalancing failed: actor type is not registered"}
{"level":"debug","ts":"2024-08-30T08:51:25Z","msg":"node=(192.168.0.123:3320) has found peer=(192.168.0.106:3320)"}
{"level":"debug","ts":"2024-08-30T08:51:25Z","msg":"total actors: 2 on node left[172.16.23.26:3320]"}
{"level":"debug","ts":"2024-08-30T08:51:25Z","msg":"re-creating actor=[(mbp2024.local-ping) of type (actors.pid)]"}
{"level":"error","ts":"2024-08-30T08:51:25Z","msg":"actor type is not registered"}
{"level":"error","ts":"2024-08-30T08:51:25Z","msg":"cluster rebalancing failed: actor type is not registered"}
```

Why the re-balancing search for type "actors.pid" and not "main.Ping", which is the correct type?

**Comment by Tochemey** [comment]
This is interesting. Let take a look at it. I was about to run some QA.

**Comment by Tochemey** [comment]
Bug fixed. closing the issue.

**Comment by webfrank** [comment]
Hi, it worked like a charm. One thing to get noted in the documentation is Actors which should be re-balanced cannot be created with parameters as the system will not re-create them this way.

Thank you for your support.

**Comment by Tochemey** [comment]
@webfrank I have cut a new release https://github.com/Tochemey/goakt/releases/tag/v2.6.1 that includes that fix. Please do you mind open a PR regarding the documentation. I did not get well what you are suggesting. Thanks
