### ISSUE TITLE
[FEAT] Uniform Local/Remote Tell/Ask

### ISSUE THREAD

**Issue by webfrank** [Tochemey/goakt#450]
**Problem description**
I was trying to implement a simple cluster with message passing and found my self struggling upon Tell/RemoteTell (and Ask/RemoteAsk) semantic.

On first try I created a non cluster environment, using Tell, after a while I switched to cluster and should change the code to use RemoteTell with the remote actor address found using something like `actor, _, _ := p.actorSystem.ActorOf(ctx.Context(), "<actor name>")`.

**Solution description**
Why not define a cleaner interface (Send / Request, just to not break Tell/Ask) which accept the actor name and not PID (if local) or address if remote?

The two methods could be used indifferently on local only, remote and cluster deployment without changing the code.

The method could use a distributed to cache to prevent too much query for PID/address and re-query only if the first try fails (as an example).

**Alternative solutions**
The only alternative I see, possibly wrong, is to ask every time for actor address and use Remote* everywhere.

**Additional context**
Nothing here

**Comment by Tochemey** [comment]
@webfrank I will be glad if you can contribute with a PR 😏

**Comment by webfrank** [comment]
Will try not to break something.

**Comment by Tochemey** [comment]
@webfrank I have started the work in this PR https://github.com/Tochemey/goakt/pull/454. It should take me some days to complete it. However there will be a major breaking change once completed.

**Comment by webfrank** [comment]
I was studying the code and I thought to implement the two methods in PID interface with reference in receive context as the others. 

To not break too much I was thinking to re-use Tell/RemoteTell and Ask/RemoteAsk inside the new methods. 

The logic inside could be: if ActorOf returns PID use Tell/Ask otherwise RemoteTell/RemoteAsk. To not query all the times the cluster I was thinking of using Olric distributes map to cache the response of ActorOf. If Tell/Ask fails (because the Actor is no more local or at a different address) reiterate ActorOf and update cache. 

Obviously this from a first analysis of the code, probably there is a better way to implement it.

**Comment by Tochemey** [comment]
@webfrank Yeah we can do that. However we will be offering too many methods to achieve the same thing. Also I don't think we should cache because Olric already offering cache under the hood.

**Comment by Tochemey** [comment]
@webfrank I am done with the implementation. Just need to add the unit tests. You can check the PR and tell me whether this looks ok. :)

**Comment by Tochemey** [comment]
@webfrank The methods are added and merged. Thanks for the suggestion. In the coming days I will look into consolidation of methods.
