### ISSUE TITLE
[FEAT]Rewrite the cluster engine

### ISSUE THREAD

**Issue by Tochemey** [Tochemey/goakt#465]
Make use of gRPC and hashicorp memberlist to rewrite the new cluster engine. 

1. Use hashicorp memberlist to broadcast node's actors amongst peers
2. Use gRPC/connectrpc to communicate between nodes. There will be some eventual consistency here
3. Use the same service discovery mechanism to initially discover nodes
4. Emit cluster events

**Comment by sdil** [comment]
Just curious,what's the motivation of using grpc and memberlist instead of keeping with current implementation?

**Comment by Tochemey** [comment]
@sdil the current implementation is good and does the job. However there is some sort key duplication processing ongoing:

- Distribute an actor in the cluster
- Distribute node state in the cluster for easy redeployment

We could combine these two in one and avoid many TCP pull/sync calls

I am still looking into the best approach but I think the current implementation can be better.

**Comment by Tochemey** [comment]
Using memberlist and gRPC node state can via single TCP push/pull can be replicated amongst the peers and with the help of a simple DHT we can perform unique lookup of actor. By the way these are just the first thoughts I have at the moment :)

**Comment by Tochemey** [comment]
@sdil I have started some work here https://github.com/Tochemey/gokv that will help in this feature.

**Comment by sdil** [comment]
This looks good! I assume that this will replace Olric, right?

**Comment by Tochemey** [comment]
> This looks good! I assume that this will replace Olric, right?

Yeah that is the plan :)

**Comment by Tochemey** [comment]
@sdil the new thing in view at the moment is to get some high throughput and refactor Go-Akt to always start in cluster mode even if it is one node.

**Comment by Tochemey** [comment]
closing this issue for the meantime. I will circle back on it when necessary
