### ISSUE TITLE
[FEAT] Clarification on supervisor lifecycle

### ISSUE THREAD

**Issue by webfrank** [Tochemey/goakt#513]
**Problem description**
I would like to better understand the supervisor lifecycle. I finally manage to start a real project with this lib and, for the moment, I'm using a single node, no cluster. 
I understood the supervisor will restart an Actor if it panics for any reason. This is not the case, if the Actor panics the program exits.

**Solution description**
If I set `goakt.WithSupervisorDirective(goakt.NewResumeDirective()))` I expect any failing Actor to be resumed.

**Alternative solutions**

**Additional context**

**Comment by Tochemey** [comment]
@webfrank I hope this helps.

**Comment by Tochemey** [comment]
@webfrank can you elaborate a bit on this statement:
`I understood the supervisor will restart an Actor if it panics for any reason. This is not the case, if the Actor panics the program exits.`

**Comment by webfrank** [comment]
Hi, when I first tested the framework in cluster mode I was able to shutdown a node and all the running actors were rescheduled on the remaining ones. 
I suppose the Supervisor process will try to restart an Actor if it fails for any reason. 
In the actual project, only one node without cluster, I had an Actor panic due to wrong code and the whole program exited. 
I was convinced the Supervisor actor would recover any Actor panics respawning the failing one but more importantly without panic the system. 
This was my idea of the Supervisor. I didn't have a chance to dig the relevant piece of code but will do it to better understand the overall lifecycle. 
From other Actor frameworks, Erlang in primis, an Actor should be able to fail without compromising the system, it could not be restarted by the Supervisor (this could be a configuration option) but never should cause program exit IMO.

**Comment by Tochemey** [comment]
> I had an Actor panic due to wrong code and the whole program exited.
> I was convinced the Supervisor actor would recover any Actor panics respawning the failing one but more importantly without panic the system.

The whole program exited may be due to an implementation issue in the program because. This is the whole set of unit tests that cover the supervisor implementation https://github.com/Tochemey/goakt/blob/main/actors/pid_test.go#L396-L740. I will try to see whether I can reproduce your issue.

**Comment by Tochemey** [comment]
@webfrank It also worth pointing out that the supervisor feature in GoAkt only take care of faulty actor which means actor during message processing panics. As stated [here](https://github.com/Tochemey/goakt/issues/513#issuecomment-2468748073) this is the current behvior. However I am not disputing a possible bug in the implementation. I can only reproduce it if I have a sample code that you can share with me.

**Comment by webfrank** [comment]
Hi, this was my test code:

```go
package main

import (
	"context"
	"os"
	"os/signal"
	"time"

	goakt "github.com/tochemey/goakt/v2/actors"
	"github.com/tochemey/goakt/v2/goaktpb"
	"github.com/tochemey/goakt/v2/log"
)

type Proxy struct {
	self   *goakt.PID
	ctx    context.Context
	cancel context.CancelFunc
}

func NewProxy() *Proxy {
	return &Proxy{}
}

func (p *Proxy) PreStart(context.Context) (err error) {
	log.DefaultLogger.Info("Starting Proxy")

	return
}

func (p *Proxy) Receive(ctx *goakt.ReceiveContext) {
	switch ctx.Message().(type) {
	case *goaktpb.PostStart:
		p.self = ctx.Self()
		p.ctx, p.cancel = context.WithCancel(context.Background())

	case *goaktpb.Broadcast:
		panic("broadcast")
	default:
		ctx.Unhandled()
	}
}

func (p *Proxy) PostStop(context.Context) error {
	log.DefaultLogger.Info("Stopping Proxy")
	p.cancel()

	return nil
}

func main() {
	ctx := context.Background()

	logger := log.DefaultLogger

	// create the actor system.
	actorSystem, err := goakt.NewActorSystem("landscape",
		goakt.WithLogger(logger),
		goakt.WithPassivationDisabled(),
		goakt.WithActorInitMaxRetries(3),
		goakt.WithSupervisorDirective(goakt.NewResumeDirective()))
	if err != nil {
		panic(err)
	}

	// start the actor system
	err = actorSystem.Start(ctx)
	if err != nil {
		panic(err)
	}

	// start proxy
	pid, err := actorSystem.Spawn(ctx, "Proxy", NewProxy())
	if err != nil {
		panic(err)
	}
	logger.Info("[PROXY] Spawned")

	// wait for ctrl+c and exit
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)

	time.AfterFunc(10*time.Second, func() {
		pid.SendAsync(ctx, "Proxy", &goaktpb.Broadcast{})
	})

	<-c
	err = actorSystem.Stop(ctx)
	if err != nil {
		logger.Errorf("app stopped with error: %v", err)
	} else {
		logger.Info("app exited")
	}
}
```

With latest version of the lib it does not panic any more. Really glad it works now as expected.

```
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"starting messages scheduler..."}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"messages scheduler started.:)"}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"Initialization process has started..."}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"starting the system supervisor actor"}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"Initialization process successfully completed."}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"landscape started..:)"}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"Initialization process has started..."}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"system supervisor successfully started"}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"Starting Proxy"}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"Initialization process successfully completed."}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"[PROXY] Spawned"}
{"level":"info","ts":"2024-11-18T09:14:58+01:00","msg":"janitor has started..."}
{"level":"error","ts":"2024-11-18T09:15:08+01:00","msg":"child actor=(goakt://landscape@127.0.0.1:0/Proxy) is failing: Err=broadcast"}
```

Great job!
