### ISSUE TITLE
Missing timeout in SendSync

### ISSUE THREAD

**Issue by webfrank** [Tochemey/goakt#514]
**Bug description**
PID.SendSync has a fixed timeout of 20 seconds.

**How to reproduce it?**
Send a message to a mailbox which will not reply.

**Expected behavior**
This should be a configurable parameter, with a 20 secs default value.

**Screenshots**

**Library Version:**
 - Go-Akt version: 2.7.1
 - Go version: 1.23

**Additional context**
I would like to know how to send a ctx.Response() which is an error. Now I'm using this code:

```go
resp, err := d.getDevices()
if err != nil {
	ctx.Err(err)
} else {
	ctx.Response(resp)
}
```

but the receiver will timeout if ctx.Err(err) is used, I expect to have an error instead to signal an issue.

**Comment by Tochemey** [comment]
@webfrank I will take a look at the issue and get back to you. Also can you point me to the hard-coded 20 seconds path?

**Comment by Tochemey** [comment]
The reply timeout is set when creating the actor system. It is a timeout that is applied to any ask-pattern message in the system. It can be set https://github.com/Tochemey/goakt/blob/v2.7.1/actors/option.go#L68. The default value is `20 seconds` as you stated.

**Comment by Tochemey** [comment]
@webfrank kindly take a look at the example in the cluster code to see how the ask-pattern works: https://github.com/Tochemey/goakt-examples/blob/main/actor-cluster/static/actors/actors.go. I will be glad to provide further explanation.

**Comment by webfrank** [comment]
> The reply timeout is set when creating the actor system. It is a timeout that is applied to any ask-pattern message in the system. It can be set https://github.com/Tochemey/goakt/blob/v2.7.1/actors/option.go#L68. The default value is `20 seconds` as you stated.

Hi, I think it could be useful to set it on a per message basis, having more control on it.

**Comment by webfrank** [comment]
> @webfrank kindly take a look at the example in the cluster code to see how the ask-pattern works: https://github.com/Tochemey/goakt-examples/blob/main/actor-cluster/static/actors/actors.go. I will be glad to provide further explanation.

Hi, I've already implemented the examples. What I was trying to achieve is to return back an error instead of waiting timeout. 

If a receiving actor wants to reply with an error the only thing could do is calling ctx.Err() but this does not cancel the context and does not returns  the error. This way the caller should wait for the timeout.

**Comment by Tochemey** [comment]
@webfrank fair point. I can look into that.

**Comment by Tochemey** [comment]
@webfrank are you free for a quick call?

**Comment by webfrank** [comment]
> @webfrank are you free for a quick call?

Hi, sorry, dinner time. I'm CET timezone. I'll send a DM with my contacts.

**Comment by Tochemey** [comment]
@webfrank I have refactored the code a bit in this [PR](https://github.com/Tochemey/goakt/pull/515) to address the timeout issue. You may have to use the latest commit hash when I merge it because I am not planning to cut a release tag soon until the christmas period because I am planning some changes in the library.

**Comment by Tochemey** [comment]
`ctx.Err(err)` is recommended instead of calling `panic`. This will trigger the supervisor to handle the faulty actor.

**Comment by Tochemey** [comment]
@webfrank kindly use this commit hash [9760b03](https://github.com/Tochemey/goakt/commit/9760b0316f24d9bbb2bb9b84b1e6cac1f41bdd46) for the meantime. I will cut a release tag a bit later.

**Comment by Tochemey** [comment]
@webfrank kindly use the latest release `2.8.0`
