### ISSUE TITLE
[FEAT]StatefulActor API

### ISSUE THREAD

**Issue by Tochemey** [Tochemey/goakt#560]
**Problem description**
There is lack of a convenient API to build a stateful actor. The current design can easily leads to build one if the developer needs to.

**Solution description**
The goal of this feature is to provide a convenient API to build stateful actors. At the moment one can use [eGo](https://github.com/Tochemey/ego) to build an event sourcing/CQRS applications. However there are use cases where a simple state management is really necessary which is a common thing in the industry. One just needs react to a command and produce a new state and let that state be persisted into a durable store.

**Alternative solutions**
Use the current GoAkt features to hack it.

**Additional context**

**Comment by Tochemey** [comment]
closing this feature because it requires some deep thinking. At the moment I really don't have the time to think this through.

**Comment by Tochemey** [comment]
@sdil thanks for loving this feature. I have added that feature to [eGo](https://github.com/Tochemey/ego) which is the best place to have it. The [PR](https://github.com/Tochemey/ego/pull/100) has been merged. Yet to cut a release maybe later this week.

**Comment by sdil** [comment]
@Tochemey I tried it and it looks great! I liked it
